apiVersion: v2
name: ephmrl
description: A Helm chart for ephmrl
type: application
version: 0.0.8
appVersion: "0.0.8"
dependencies:
  - name: api
    version: "0.0.8"
    repository: file://charts/api