apiVersion: v2
name: ephmrl
description: A Helm chart for ephmrl
type: application
version: 0.0.4
appVersion: "0.0.4"
dependencies:
  - name: api
    version: "0.0.4"
    repository: file://charts/api