"""add maximum tenants column in llm instances

Revision ID: 2044729ed745
Revises: 53021582e4ed
Create Date: 2025-11-17 16:52:53.453593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2044729ed745'
down_revision: Union[str, Sequence[str], None] = '53021582e4ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_instances', sa.Column('maximum_tenants', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_instances', 'maximum_tenants')
    # ### end Alembic commands ###
