"""create gpu, hosting, llm, machine, project tables

Revision ID: 53021582e4ed
Revises: 8968f75c2846
Create Date: 2025-11-15 15:36:51.820865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53021582e4ed'
down_revision: Union[str, Sequence[str], None] = '8968f75c2846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosting_contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('price_per_hour', sa.Integer(), nullable=False),
    sa.Column('org_verification_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expiring_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listed_llms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('image_location', sa.String(length=255), nullable=True),
    sa.Column('base_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('base_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('listed_llm_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['listed_llm_id'], ['listed_llms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_subinstances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('llm_instance_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('credit_price_per_hour', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_dedicated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['llm_instance_id'], ['llm_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_subinstances_org_created', 'llm_subinstances', ['org_id', 'created_at'], unique=False)
    op.create_index('ix_llm_subinstances_user', 'llm_subinstances', ['user_id'], unique=False)
    op.create_table('machines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('provider_type', sa.String(length=100), nullable=False),
    sa.Column('hosted_by_org_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_number_of_gpus', sa.Integer(), nullable=False),
    sa.Column('available_number_of_gpus', sa.Integer(), nullable=False),
    sa.Column('hosting_contract_id', sa.UUID(), nullable=True),
    sa.Column('specs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hosted_by_org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['hosting_contract_id'], ['hosting_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_machines_ip_address', 'machines', ['ip_address'], unique=False)
    op.create_index('ix_machines_name', 'machines', ['name'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('additional_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gpus',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vram_gb', sa.Integer(), nullable=False),
    sa.Column('cuda_cores', sa.Integer(), nullable=False),
    sa.Column('specs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_utilization', sa.Integer(), nullable=False),
    sa.Column('max_utilization', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('machine_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiring_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gpus_name', 'gpus', ['name'], unique=False)
    op.create_table('llm_instance_gpus',
    sa.Column('llm_instance_id', sa.UUID(), nullable=False),
    sa.Column('gpu_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['gpu_id'], ['gpus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['llm_instance_id'], ['llm_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('llm_instance_id', 'gpu_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llm_instance_gpus')
    op.drop_index('ix_gpus_name', table_name='gpus')
    op.drop_table('gpus')
    op.execute('DROP TABLE IF EXISTS projects CASCADE')
    op.drop_index('ix_machines_name', table_name='machines')
    op.drop_index('ix_machines_ip_address', table_name='machines')
    op.drop_table('machines')
    op.drop_index('ix_llm_subinstances_user', table_name='llm_subinstances')
    op.drop_index('ix_llm_subinstances_org_created', table_name='llm_subinstances')
    op.drop_table('llm_subinstances')
    op.drop_table('llm_instances')
    op.drop_table('listed_llms')
    op.drop_table('hosting_contracts')
    # ### end Alembic commands ###
