"""remove column_name from table_name

Revision ID: a840737e9cc9
Revises: 18acf2ea5608
Create Date: 2025-11-11 17:15:02.541051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a840737e9cc9'
down_revision: Union[str, Sequence[str], None] = '18acf2ea5608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_service_account')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_service_account', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
