{{- if .Values.imagePullSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  labels:
    app.kubernetes.io/name: {{ include "ephmrl.name" . }}
    helm.sh/chart: {{ include "ephmrl.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecretValue }}
{{- end }}