/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as DashboardModelsRouteImport } from './routes/dashboard/models'
import { Route as DashboardDeployedRouteImport } from './routes/dashboard/deployed'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardRagRouteImport } from './routes/dashboard/_rag'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as DashboardRagDocumentsRouteImport } from './routes/dashboard/_rag/documents'
import { Route as DashboardRagChatRouteImport } from './routes/dashboard/_rag/chat'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardModelsRoute = DashboardModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDeployedRoute = DashboardDeployedRouteImport.update({
  id: '/deployed',
  path: '/deployed',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRagRoute = DashboardRagRouteImport.update({
  id: '/_rag',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRagDocumentsRoute = DashboardRagDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => DashboardRagRoute,
} as any)
const DashboardRagChatRoute = DashboardRagChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DashboardRagRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRagRouteWithChildren
  '/api/checkout': typeof ApiCheckoutRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/deployed': typeof DashboardDeployedRoute
  '/dashboard/models': typeof DashboardModelsRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard/chat': typeof DashboardRagChatRoute
  '/dashboard/documents': typeof DashboardRagDocumentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRagRouteWithChildren
  '/api/checkout': typeof ApiCheckoutRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/deployed': typeof DashboardDeployedRoute
  '/dashboard/models': typeof DashboardModelsRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard/chat': typeof DashboardRagChatRoute
  '/dashboard/documents': typeof DashboardRagDocumentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/api/checkout': typeof ApiCheckoutRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/_rag': typeof DashboardRagRouteWithChildren
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/deployed': typeof DashboardDeployedRoute
  '/dashboard/models': typeof DashboardModelsRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/_rag/chat': typeof DashboardRagChatRoute
  '/dashboard/_rag/documents': typeof DashboardRagDocumentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/api/checkout'
    | '/auth/callback'
    | '/dashboard/analytics'
    | '/dashboard/deployed'
    | '/dashboard/models'
    | '/auth'
    | '/dashboard/chat'
    | '/dashboard/documents'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/api/checkout'
    | '/auth/callback'
    | '/dashboard/analytics'
    | '/dashboard/deployed'
    | '/dashboard/models'
    | '/auth'
    | '/dashboard/chat'
    | '/dashboard/documents'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/api/checkout'
    | '/auth/callback'
    | '/dashboard/_rag'
    | '/dashboard/analytics'
    | '/dashboard/deployed'
    | '/dashboard/models'
    | '/auth/'
    | '/dashboard/_rag/chat'
    | '/dashboard/_rag/documents'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/models': {
      id: '/dashboard/models'
      path: '/models'
      fullPath: '/dashboard/models'
      preLoaderRoute: typeof DashboardModelsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/deployed': {
      id: '/dashboard/deployed'
      path: '/deployed'
      fullPath: '/dashboard/deployed'
      preLoaderRoute: typeof DashboardDeployedRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/_rag': {
      id: '/dashboard/_rag'
      path: ''
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRagRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_rag/documents': {
      id: '/dashboard/_rag/documents'
      path: '/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof DashboardRagDocumentsRouteImport
      parentRoute: typeof DashboardRagRoute
    }
    '/dashboard/_rag/chat': {
      id: '/dashboard/_rag/chat'
      path: '/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof DashboardRagChatRouteImport
      parentRoute: typeof DashboardRagRoute
    }
  }
}

interface DashboardRagRouteChildren {
  DashboardRagChatRoute: typeof DashboardRagChatRoute
  DashboardRagDocumentsRoute: typeof DashboardRagDocumentsRoute
}

const DashboardRagRouteChildren: DashboardRagRouteChildren = {
  DashboardRagChatRoute: DashboardRagChatRoute,
  DashboardRagDocumentsRoute: DashboardRagDocumentsRoute,
}

const DashboardRagRouteWithChildren = DashboardRagRoute._addFileChildren(
  DashboardRagRouteChildren,
)

interface DashboardRouteChildren {
  DashboardRagRoute: typeof DashboardRagRouteWithChildren
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardDeployedRoute: typeof DashboardDeployedRoute
  DashboardModelsRoute: typeof DashboardModelsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardRagRoute: DashboardRagRouteWithChildren,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardDeployedRoute: DashboardDeployedRoute,
  DashboardModelsRoute: DashboardModelsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ApiCheckoutRoute: ApiCheckoutRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
