
imagePullSecrets:
  - name: dockerhub-secret
imagePullSecretValue: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: ephmrl.ai
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 512Mi

livenessProbe: null
readinessProbe: null

autoscaling:
  enabled: false

configMapEnv:
  - VITE_API_URL: "https://ephmrl.ai/api"

secretEnv: []

api:
  imagePullSecrets:
    - name: dockerhub-secret
  service:
    type: ClusterIP
    port: 80
    targetPort: 8000
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/use-regex: "true"
    hosts:
      - host: ephmrl.ai
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
    tls: []
  resources:
    limits:
      cpu: 200m
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 2Gi
  autoscaling:
    enabled: false
  configMapEnv: []
  secretEnv: []
    